services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - dynamodb


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend/app
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data
    command: "-jar DynamoDBLocal.jar -sharedDb"
    working_dir: /home/dynamodblocal


volumes:
  dynamodb_data:
